---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ocs-catalogsource
  namespace: openshift-marketplace
  labels:
      ocs-operator-internal: "true"
spec:
  displayName: Openshift Container Storage
  icon:
  base64data: ""
  mediatype: ""
  image: quay.io/rhceph-dev/ocs-olm-operator:latest-4.7
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
  openshift.io/cluster-monitoring: "true"
  name: openshift-storage
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage-operatorgroup
  namespace: openshift-storage
spec:
  targetNamespaces:
  - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-subscription
  namespace: openshift-storage
spec:
  channel: stable-4.7
  config:
  resources: {}
  name: ocs-operator
  source: ocs-catalogsource
  sourceNamespace: openshift-marketplace

